name: HQS CI tests for pure rust and pure python repos

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  linting_rust:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_rust_pyo3.yml@main
  
  linting_python:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_pure_python.yml@main
    with: 
      python_folder: "qoqo_mock"
      linting_folder: "qoqo_mock/qoqo_mock"

  unittests_rust:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_unittests_rust_pyo3.yml@main
    with:
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true
      rust_package_name: "roqoqo-mock"
      test_code_coverage: false

  unittests_python:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_tests_pure_python.yml@main
    with: 
      python_folder: "qoqo_mock"
      test_code_coverage: false
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true

  manual_test_python_linux:
    name: manual_test_python_linux-${{ matrix.python.interpreter }}
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python: [
            {py: '3.7', interpreter: "python3.7"},
            {py: '3.8', interpreter: "python3.8"},
            {py: '3.9', interpreter: "python3.9"},
            {py: '3.10', interpreter: "python3.10"},
            {py: '3.11', interpreter: "python3.11"},
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.py }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install pytest numpy
      - name: Test without coverage pytest
        run: |
          cd qoqo_mock/
          pip install ./
          cd tests/
          pytest ./
