name: HQS CI tests for pure rust and pure python repos

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  linting_rust:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_rust_pyo3.yml@main
  
  linting_python:
    uses: kbarkhqs/reusable_workflows/.github/workflows/reusable_linting_pure_python.yml@main
    with: 
      python_folder: "qoqo_mock"
      linting_folder: "qoqo_mock"

  unittests_rust:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_unittests_rust_pyo3.yml@main
    with:
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true
      rust_package_name: "roqoqo-mock"
      test_code_coverage: false

  unittests_python:
    uses: kbarkhqs/reusable_workflows/.github/workflows/reusable_tests_pure_python.yml@main
    with: 
      python_folder: "qoqo_mock"
      test_code_coverage: false
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: true
