name: HQS build and deploy for pure rust and pure python repos

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  deploy_cratesio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
        cargo publish --manifest-path=roqoqo-mock/Cargo.toml

  deploy_pypi:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_pure_python.yml@main
    with: 
      python_folder: "qoqo_mock"
    secrets: inherit
